apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: node
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
